CREATE TABLE Task (
	TaskId INTEGER PRIMARY KEY AUTOINCREMENT,
	GroupId INTEGER,
	title VARCHAR(256),
	description VARCHAR(2560),
	
	FOREIGN KEY(GroupId) REFERENCES `Group`(GroupId)
);

CREATE TABLE `Group`(
	GroupId INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE Users( 
    UserId INTEGER PRIMARY KEY AUTOINCREMENT, 
    GroupId INTEGER,
    Username VARCHAR(256),
    Firstname VARCHAR(256),
    Lastname VARCHAR(256),
    UNIQUE(Username),
    FOREIGN KEY(GroupId) REFERENCES `Group`(GroupId)
);
